[package]
name = "image-optim"
version = "0.2.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
avif-decode = "0.2.2"
axum = { version = "0.6.20", features = ["multipart"] }
axum-client-ip = "0.4.2"
base64 = "0.21.4"
chrono = "0.4.30"
dssim = "3.2.4"
http = "0.2.9"
image = { version = "0.24.7", features = ["webp-encoder", "avif-encoder"]}
imagequant = { version = "4.2.0", default-features = false }
lodepng = "3.7.2"
lru = "0.10.0"
mime = "0.3.17"
mime_guess = "2.0.4"
mozjpeg = "0.9.8"
nanoid = "0.4.0"
once_cell = "1.18.0"
regex = "1.9.4"
reqwest = { version = "0.11.20", default-features = false, features = ["rustls-tls"] }
rgb = "0.8.36"
serde = { version = "1.0.188", features = ["derive"] }
snafu = "0.7.5"
substring = "1.4.5"
time = "0.3.28"
tokio = { version = "1.32.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "fs"] }
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["local-time"] }
urlencoding = "2.1.3"

[profile.release]
lto = true
codegen-units = 1 
