[package]
name = "image-optim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.0-rc.2"
base64 = "0.20.0-alpha.1"
image = { version = "0.24.4", features = ["webp-encoder", "avif-encoder"] }
imagequant = "4.0.4"
lodepng = "3.7.0"
mime = "0.3.16"
mime_guess = "2.0.4"
mozjpeg = "0.9.4"
rgb = "0.8.34"
serde = { version = "1.0.145", features = ["derive"] }
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread", "net"] }
