[package]
name = "image-optim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
avif-decode = "0.2.2"
axum = "0.6.0-rc.2"
base64 = "0.20.0-alpha.1"
dssim = "3.2.3"
http = "0.2.8"
image = { version = "0.24.4", features = ["webp-encoder", "avif-encoder"] }
imagequant = "4.0.4"
lodepng = "3.7.0"
lru = "0.8.1"
mime = "0.3.16"
mime_guess = "2.0.4"
mozjpeg = "0.9.4"
once_cell = "1.15.0"
reqwest = "0.11.12"
rgb = "0.8.34"
serde = { version = "1.0.145", features = ["derive"] }
snafu = "0.7.2"
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread", "net"] }
tower = { version = "0.4.13", features = ["timeout"]}
urlencoding = "2.1.2"
