[package]
name = "image-optim"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
avif-decode = "0.2.2"
axum = "0.6.19"
axum-client-ip = "0.4.1"
base64 = "0.21.2"
chrono = "0.4.26"
dssim = "3.2.4"
http = "0.2.9"
image = { version = "0.24.6", features = ["webp-encoder", "avif-encoder", "gif"], default-features = false}
imagequant = { version = "4.2.0", default-features = false }
lodepng = "3.7.2"
lru = "0.10.0"
mime = "0.3.17"
mime_guess = "2.0.4"
mozjpeg = "0.9.6"
nanoid = "0.4.0"
once_cell = "1.18.0"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls"] }
rgb = "0.8.36"
serde = { version = "1.0.176", features = ["derive"] }
snafu = "0.7.5"
time = "0.3.22"
tokio = { version = "1.29.1", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["local-time"] }
urlencoding = "2.1.3"

[profile.release]
lto = true
codegen-units = 1 
