[package]
name = "image-optim"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
avif-decode = "0.2.2"
axum = "0.6.18"
axum-client-ip = "0.4.1"
base64 = "0.21.2"
chrono = "0.4.24"
dssim = "3.2.4"
http = "0.2.9"
image = { version = "0.24.6", features = ["webp-encoder", "avif-encoder"] }
imagequant = "4.2.0"
lodepng = "3.7.2"
lru = "0.10.0"
mime = "0.3.17"
mime_guess = "2.0.4"
mozjpeg = "0.9.4"
nanoid = "0.4.0"
once_cell = "1.17.1"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls"] }
rgb = "0.8.36"
serde = { version = "1.0.162", features = ["derive"] }
snafu = "0.7.4"
time = "0.3.20"
tokio = { version = "1.28.2", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["local-time"] }
urlencoding = "2.1.2"

[profile.release]
strip = true 
lto = true
