[package]
name = "image-optim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
avif-decode = "0.2.2"
axum = "0.6.7"
base64 = "0.21.0"
dssim = "3.2.4"
http = "0.2.9"
image = { version = "0.24.5", features = ["webp-encoder", "avif-encoder"] }
imagequant = "4.1.0"
lodepng = "3.7.2"
lru = "0.9.0"
mime = "0.3.16"
mime_guess = "2.0.4"
mozjpeg = "0.9.4"
once_cell = "1.17.1"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls"] }
rgb = "0.8.36"
serde = { version = "1.0.152", features = ["derive"] }
snafu = "0.7.4"
tokio = { version = "1.25.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
urlencoding = "2.1.2"
