name: build

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    timeout-minutes: 600

    steps:
    - name: Change Swap Space
      run: |
        swapon --show=NAME | tail -n 1
        df -lh
        export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
        sudo swapoff $SWAP_FILE
        sudo rm $SWAP_FILE
        export SWAP_FILE=/swapfile
        sudo fallocate -l 1G $SWAP_FILE
        sudo chmod 600 $SWAP_FILE
        sudo mkswap $SWAP_FILE
        sudo swapon $SWAP_FILE
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 16
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/arm64
        tags: vicanso/image-optim
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}