name: build

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    timeout-minutes: 600

    steps:
    # pierotofy/set-swap-space@v1.0
    # easimon/maximize-build-space
    - name: Change Swap Space
      run: |
        swapon --show=NAME | tail -n 1
        df -lh
        du -sh /usr/share/dotnet
        sudo rm -rf /usr/share/dotnet
        du -sh /usr/local/lib/android
        sudo rm -rf /usr/local/lib/android 
        export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
        sudo swapoff $SWAP_FILE
        sudo rm $SWAP_FILE
        export SWAP_FILE=/swapfile
        sudo fallocate -l 32G $SWAP_FILE
        sudo chmod 600 $SWAP_FILE
        sudo mkswap $SWAP_FILE
        sudo swapon $SWAP_FILE
    - name: Swap space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free -h
        echo
        swapon --show
        df -lh
        echo
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          vicanso/image-optim
        tags: |
          type=semver,pattern={{version}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}